services:
  sdpm:
    image: sdpm_image_dev
    build:
      context: .
      dockerfile: Dockerfiles/dev/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
